# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = 'b68376af018d755a040a3ced52cb172d'
  config.secret_key = '94ea16f718b1a07e543d5d9e7da36627'
  config.default_from = 'klengvinayte@gmail.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
